from flask import Flask
from flask_restful import Resource
class Awareness(Resource):
    def get(self):
        return {'data':[
         {
             "title": 'What are the best tools and technologies to protect systems and data from cyber threats?',
             "desc":'There are several effective tools and technologies available to protect systems and data from cyber threats. Here are some of the best ones:1. Firewalls: Firewalls work by monitoring and filtering network traffic to prevent unauthorized access to systems and networks.2. Antivirus and Anti-malware Software: These programs detect and remove malicious software and viruses from systems.3. Security Software Updates: Regularly updating software and systems helps protect them from known security vulnerabilities.4. Intrusion Detection Systems: These systems monitor network traffic and detect unauthorized or suspicious activities.5. Identity and Access Management: This technology controls access to systems and data, assigning specific permissions to users and roles.6. Encryption: Encryption is used to secure data by making it unreadable or inaccessible to unauthorized individuals.7. Backup and Data Recovery: Creating backups of sensitive data ensures its recovery in case of a security breach or system failure.8. Penetration Testing: Ethical hacking teams use penetration testing to assess systems and infrastructure, identify vulnerabilities, and provide recommendations for strengthening security.9. Threat Intelligence: Utilizing available information sources, threat intelligence helps identify and monitor cyber threats, enabling proactive measures to prevent them.10. Security Training and Awareness: Promoting awareness and providing training to users helps them recognize cyber threats and take necessary precautions.',
              "image": 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnD9CBdDsj3BSR53RvurqxSEDNg2J3iCuIRw&usqp=CAU',
          },
         {
             "title":' What are some signs that could indicate that an email is malicious?',
             "desc":'Here are some signs that could indicate that an email is malicious:1. Suspicious Sender: If the email is from an unknown sender or a suspicious email address that doesnt match the organization it claims to be from, it could be a red flag.2. Poor Grammar and Spelling: Malicious emails often contain numerous grammar mistakes, spelling errors, or awkward language usage. This can indicate that the email is not from a legitimate source.3. Requests for Personal Information: Be cautious if the email asks for sensitive personal information such as passwords, Social Security numbers, or financial details. Legitimate organizations typically do not request such information via email.4. Urgency or Fear Tactics: Malicious emails may use urgent language, threats, or fear tactics to pressure you into taking immediate action. They may attempt to create a sense of urgency or manipulate your emotions.5. Unexpected Attachments or Links: Be wary of email attachments or links that you were not expecting or that seem out of context. Malicious attachments can contain malware, and deceptive links can lead to phishing websites.6. Unusual Requests or Scenarios: Emails that request unusual actions, such as wiring money, transferring funds, or providing access to sensitive systems, should be treated with caution. Verify such requests through other means before taking any action.7. Mismatched URLs: Hover over links in the email to see the actual URL destination. If the displayed URL doesnt match the links description or if it leads to a suspicious website, it may be a phishing attempt.8. Impersonation of Trusted Entities: Malicious emails may impersonate well-known companies, government agencies, or individuals to gain your trust. Pay attention to slight variations or misspellings in the senders name or email address.9. Unusual Email Formatting: Emails that have strange formatting, unusual fonts, or inconsistent branding may be indicators of a malicious email.10. Unexpected or Unusual Content: If the email contains content that seems irrelevant, inappropriate, or nonsensical, it could be a sign of a malicious email.Its important to exercise caution and use common sense when evaluating the legitimacy of an email. If you suspect an email to be malicious, it is best to delete it or report it to your organizations IT or security team. ',
              "image":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVQ7pwcMSSXqoyTrWK_cAIWFdihzGkNn_tVw&usqp=CAU',
          },
       ]}